import { describe, it, expect } from 'vitest';
import { parseSchedule } from './parseSchedule';

describe('parseSchedule', () => {
  it('should parse standard pipe-separated format', () => {
    const input = 'TTH | 9:00AM-10:30AM | ROOM';
    const result = parseSchedule(input);
    expect(result).not.toBeNull();
    expect(result.allTimeSlots).toHaveLength(1);
    expect(result.allTimeSlots[0].days).toEqual(['T', 'TH']);
  });

  it('should parse Variation 1 format (Space separated, no pipes)', () => {
    // "F 9:00AM-10:30AM RTL313 LEC"
    const input = 'F 9:00AM-10:30AM RTL313 LEC';
    const result = parseSchedule(input);
    expect(result).not.toBeNull();
    expect(result.allTimeSlots).toHaveLength(1);
    expect(result.allTimeSlots[0].days).toEqual(['F']);
    expect(result.allTimeSlots[0].startTime).toBe('09:00');
    expect(result.allTimeSlots[0].endTime).toBe('10:30');
  });

  it('should parse Variation 2 format (Combined space separated)', () => {
    // "F 9:00AM-10:30AM RTL313 LEC T 9:00AM-10:30AM RTL313 LEC"
    const input = 'F 9:00AM-10:30AM RTL313 LEC T 9:00AM-10:30AM RTL313 LEC';
    const result = parseSchedule(input);
    expect(result).not.toBeNull();
    expect(result.allTimeSlots).toHaveLength(2);

    // Slot 1
    const slot1 = result.allTimeSlots.find((s) => s.days.includes('F'));
    expect(slot1).toBeDefined();
    expect(slot1.startTime).toBe('09:00');

    // Slot 2
    const slot2 = result.allTimeSlots.find((s) => s.days.includes('T'));
    expect(slot2).toBeDefined();
    expect(slot2.startTime).toBe('09:00');
  });

  describe('Compact schedule strings (from parseCompactVariation)', () => {
    it('should parse schedule string generated by parseCompactVariation', () => {
      const scheduleStr = 'WFM | 08:00 AM - 12:00 PM | FIELD | LEC (In-Person)';
      const result = parseSchedule(scheduleStr);

      expect(result).not.toBeNull();
      expect(result.allTimeSlots).toHaveLength(1);
      expect(result.allTimeSlots[0].days).toEqual(['F', 'M', 'W']); // Sorted
      expect(result.allTimeSlots[0].startTime).toBe('08:00');
      expect(result.allTimeSlots[0].endTime).toBe('12:00');
      expect(result.allTimeSlots[0].room).toBe('FIELD');
    });

    it('should handle TTHS day format', () => {
      const scheduleStr = 'TTHS | 08:00 AM - 12:00 PM | FIELD | LEC (In-Person)';
      const result = parseSchedule(scheduleStr);

      expect(result).not.toBeNull();
      expect(result.allTimeSlots[0].days).toEqual(['S', 'T', 'TH']); // Sorted
    });

    it('should handle THST day format', () => {
      const scheduleStr = 'THST | 01:00 PM - 05:00 PM | FIELD | LEC (In-Person)';
      const result = parseSchedule(scheduleStr);

      expect(result).not.toBeNull();
      expect(result.allTimeSlots[0].days).toEqual(['S', 'T', 'TH']); // Sorted: S, T, TH
      expect(result.allTimeSlots[0].startTime).toBe('13:00');
      expect(result.allTimeSlots[0].endTime).toBe('17:00');
    });

    describe('Complex/Hybrid Schedules (from console logs)', () => {
      it('should handle comma-separated days and duplicate times', () => {
        const scheduleStr =
          'M, TH | 03:00 PM - 04:30 PM, 03:00 PM - 04:30 PM | ACAD309, ONLINE | LAB, LAB (HYBRID)';
        const result = parseSchedule(scheduleStr);
        expect(result).not.toBeNull();
        // Should collapse to 2 slots (M and TH) sharing the same time
        expect(result.allTimeSlots).toHaveLength(2);
        expect(result.allTimeSlots[0].startTime).toBe('15:00');
        expect(result.representativeDays).toContain('M');
        expect(result.representativeDays).toContain('TH');
      });

      it('should handle mismatched comma-separated days and times', () => {
        const scheduleStr =
          'M, W | 08:00 AM - 10:00 AM, 07:30 AM - 10:30 AM | CASEROOM, NGE102 | LAB, LEC (IN-PERSON)';
        const result = parseSchedule(scheduleStr);
        expect(result).not.toBeNull();
        expect(result.allTimeSlots).toHaveLength(2);
        // Slot 1: M -> 08:00-10:00
        expect(result.allTimeSlots[0].days).toEqual(['M']);
        expect(result.allTimeSlots[0].startTime).toBe('08:00');
        // Slot 2: W -> 07:30-10:30
        expect(result.allTimeSlots[1].days).toEqual(['W']);
        expect(result.allTimeSlots[1].startTime).toBe('07:30');
      });

      it('should handle hybrid rooms in forward order', () => {
        const scheduleStr =
          'M, TH | 10:30 AM - 12:00 PM, 10:30 AM - 12:00 PM | ACAD311, ONLINE | LAB, LAB (Hybrid)';
        const result = parseSchedule(scheduleStr);
        expect(result).not.toBeNull();
        expect(result.allTimeSlots).toHaveLength(2);
        // Slot 1: M -> ACAD311
        expect(result.allTimeSlots[0].days).toEqual(['M']);
        expect(result.allTimeSlots[0].room).toBe('ACAD311');
        // Slot 2: TH -> ONLINE
        expect(result.allTimeSlots[1].days).toEqual(['TH']);
        expect(result.allTimeSlots[1].room).toBe('ONLINE');
      });
    });
  });
});
